# Generated by Django 4.0.3 on 2022-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('exchange', models.TextField()),
                ('download_datetime', models.TextField()),
            ],
        ),
    ]
